version: '2.1'

services:
  mysql:
    image: bitnami/mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
      - './sql:/docker-entrypoint-initdb.d'
      - './my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=Mysql1!.
      - MYSQL_USER=nbia_user
      - MYSQL_PASSWORD=nbia_password
      - MYSQL_DATABASE=nbiadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  tomcat:
    image: jrutecht/tomcat8:latest
    ports:
      - '24080:24080'
      - '8080:8080'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - JAVA_OPTS=-Xms2048m -Xmx2048m
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
  solr:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_AUTHENTICATION=no
      - SOLR_CORE_CONF_DIR=/opt/solr_conf
      - SOLR_CORES=nbia
    volumes:
      - './solr_cores:/opt/solr_conf'
    ports:
      - '8983:8983'
volumes:
  mysql_data:
    driver: local