version: '2.1'

services:
  mysql:
    image: bitnami/mariadb:10.5.9
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - './sql:/docker-entrypoint-initdb.d'
      - './my.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=Mysql1!.
      - MARIADB_USER=nbia_user
      - MARIADB_PASSWORD=nbia_password
      - MARIADB_DATABASE=nbiadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  tomcat:
    image: jrutecht/nbiatomcat:latest
    volumes:
      - './dicoms:/opt/dicoms'
    ports:
      - '24080:24080'
      - '8080:8080'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - JAVA_OPTS=-Djava.security.auth.login.config=/usr/local/tomcat/conf/jaas.config -Dlog4j.configuration=/usr/local/tomcat/lib/log4j.properties
  openldap:
    image: bitnami/openldap:2
    volumes:
      - './ldapconf:/opt/ldapconf'
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      # - LDAP_USERS=user01,user02,nbiaAdmin
      # - LDAP_PASSWORDS=password1,password2,admin
      - LDAP_CUSTOM_LDIF_DIR=/opt/ldapconf/nbia.ldif
  solr:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_AUTHENTICATION=no
      - SOLR_CORE_CONF_DIR=/opt/solr_conf
      - SOLR_CORES=nbia
    volumes:
      - './solr_cores:/opt/solr_conf'
    ports:
      - '8983:8983'
volumes:
  mariadb_data:
    driver: local