apiVersion: v1
kind: Service
metadata:
  labels:
    name: nbia
    prism: nbia
  name: nbia
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    name: nbia
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nbia
  template:
    metadata:
      labels:
        name: nbia
        prism: nbia
    spec:
      volumes:
      - name: nbia-webapp-storage
        persistentVolumeClaim:
          claimName: nbia-webapp-pv-claim-auto
      - name: nbia-log-storage
        persistentVolumeClaim:
          claimName: nbia-log-pv-claim-auto
      containers:
        - image: jrutecht/nbia:latest
          imagePullPolicy: Always
          name: nbia
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
          - name: nbia-webapp-storage
            mountPath: /opt/bitnami/tomcat/webapps
          - name: nbia-log-storage
            mountPath: /opt/bitnami/tomcat/logs
      restartPolicy: Always
status: {}

