---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbia-webapp-pv-claim-auto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbia-log-pv-claim-auto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
